In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense
from sklearn.metrics import mean_squared_error,mean_absolute_error
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [ ]:
df=pd.read_csv('Housing.csv')

In [ ]:
df.head()

      price  area  bedrooms  ...  parking  prefarea furnishingstatus
0  13300000  7420         4  ...        2       yes        furnished
1  12250000  8960         4  ...        3        no        furnished
2  12250000  9960         3  ...        2       yes   semi-furnished
3  12215000  7500         4  ...        3       yes        furnished
4  11410000  7420         4  ...        2        no        furnished

[5 rows x 13 columns]

In [ ]:
df.shape

(545, 13)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [ ]:
df.describe()

              price          area  ...     stories     parking
count  5.450000e+02    545.000000  ...  545.000000  545.000000
mean   4.766729e+06   5150.541284  ...    1.805505    0.693578
std    1.870440e+06   2170.141023  ...    0.867492    0.861586
min    1.750000e+06   1650.000000  ...    1.000000    0.000000
25%    3.430000e+06   3600.000000  ...    1.000000    0.000000
50%    4.340000e+06   4600.000000  ...    2.000000    0.000000
75%    5.740000e+06   6360.000000  ...    2.000000    1.000000
max    1.330000e+07  16200.000000  ...    4.000000    3.000000

[8 rows x 6 columns]

In [ ]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [ ]:
x=df.drop('price',axis=1)
y=df['price']

In [ ]:
numeric_features=['area','bedrooms','bathrooms','stories','parking']
categorical_features=['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea','furnishingstatus']

In [ ]:
preprocessor=ColumnTransformer(
    transformers=[
        ("num",StandardScaler(),numeric_features),
        ("cat",OneHotEncoder(handle_unknown='ignore'),categorical_features)
    ]
)

In [ ]:
x_processed=preprocessor.fit_transform(x);

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x_processed,y,test_size=0.20,random_state=42)

In [ ]:
model=Sequential([
    Dense(64,activation="relu",input_shape=(x_train.shape[1],)),
    Dense(32,activation="relu"),
    Dense(16,activation="relu"),
    Dense(1)
])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.compile(optimizer="adam",loss="mse",metrics=["mae"])

In [ ]:
History=model.fit(x_train,y_train,epochs=100,batch_size=32,validation_split=0.2,verbose=1)

Epoch 1/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 3s 26ms/step - loss: 25349383520256.0000 - mae: 4727421.5000 - val_loss: 24781588004864.0000 - val_mae: 4623896.0000
Epoch 2/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25349366743040.0000 - mae: 4727420.0000 - val_loss: 24781567033344.0000 - val_mae: 4623894.0000
Epoch 3/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25349343674368.0000 - mae: 4727417.5000 - val_loss: 24781535576064.0000 - val_mae: 4623891.0000
Epoch 4/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25349299634176.0000 - mae: 4727412.0000 - val_loss: 24781476855808.0000 - val_mae: 4623884.0000
Epoch 5/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25349219942400.0000 - mae: 4727404.0000 - val_loss: 24781369901056.0000 - val_mae: 4623872.5000
Epoch 6/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25349075238912.0000 - mae: 4727388.5000 - val_loss: 24781183254528.0000 - val_mae: 4623853.0000
Epoch 7/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25348829872128.0000 - mae: 4727363.5000 - val_loss: 24780874973184.0000 - val_mae: 4623820.5000
Epoch 8/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25348437704704.0000 - mae: 4727322.0000 - val_loss: 24780388433920.0000 - val_mae: 4623770.0000
Epoch 9/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25347821142016.0000 - mae: 4727258.5000 - val_loss: 24779641847808.0000 - val_mae: 4623692.5000
Epoch 10/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25346879520768.0000 - mae: 4727163.0000 - val_loss: 24778542940160.0000 - val_mae: 4623578.5000
Epoch 11/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25345510080512.0000 - mae: 4727024.0000 - val_loss: 24776970076160.0000 - val_mae: 4623416.5000
Epoch 12/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25343612157952.0000 - mae: 4726829.5000 - val_loss: 24774778552320.0000 - val_mae: 4623192.0000
Epoch 13/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25340961357824.0000 - mae: 4726563.0000 - val_loss: 24771846733824.0000 - val_mae: 4622891.5000
Epoch 14/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25337415073792.0000 - mae: 4726207.5000 - val_loss: 24767987974144.0000 - val_mae: 4622495.5000
Epoch 15/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25332889419776.0000 - mae: 4725746.0000 - val_loss: 24762950615040.0000 - val_mae: 4621982.0000
Epoch 16/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25326998519808.0000 - mae: 4725152.5000 - val_loss: 24756617216000.0000 - val_mae: 4621335.0000
Epoch 17/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25319658487808.0000 - mae: 4724409.5000 - val_loss: 24748702564352.0000 - val_mae: 4620529.5000
Epoch 18/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25310537973760.0000 - mae: 4723493.0000 - val_loss: 24739009527808.0000 - val_mae: 4619543.0000
Epoch 19/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25299569868800.0000 - mae: 4722380.5000 - val_loss: 24727192076288.0000 - val_mae: 4618343.5000
Epoch 20/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25286139707392.0000 - mae: 4721028.5000 - val_loss: 24713107603456.0000 - val_mae: 4616910.5000
Epoch 21/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25270201352192.0000 - mae: 4719421.0000 - val_loss: 24696433147904.0000 - val_mae: 4615213.0000
Epoch 22/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25251408773120.0000 - mae: 4717528.0000 - val_loss: 24676787027968.0000 - val_mae: 4613217.0000
Epoch 23/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 25229566935040.0000 - mae: 4715316.0000 - val_loss: 24653806436352.0000 - val_mae: 4610886.0000
Epoch 24/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 25203641942016.0000 - mae: 4712737.0000 - val_loss: 24627495567360.0000 - val_mae: 4608211.0000
Epoch 25/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 25174317465600.0000 - mae: 4709767.5000 - val_loss: 24597011365888.0000 - val_mae: 4605114.0000
Epoch 26/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 25140337311744.0000 - mae: 4706349.0000 - val_loss: 24562293014528.0000 - val_mae: 4601584.0000
Epoch 27/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 25101588234240.0000 - mae: 4702477.0000 - val_loss: 24523007066112.0000 - val_mae: 4597586.0000
Epoch 28/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 25057854226432.0000 - mae: 4698067.5000 - val_loss: 24478515986432.0000 - val_mae: 4593054.0000
Epoch 29/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 25008699080704.0000 - mae: 4693118.5000 - val_loss: 24428400345088.0000 - val_mae: 4587955.5000
Epoch 30/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 24953143427072.0000 - mae: 4687549.5000 - val_loss: 24372551090176.0000 - val_mae: 4582264.5000
Epoch 31/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 24892279881728.0000 - mae: 4681343.5000 - val_loss: 24309848342528.0000 - val_mae: 4575880.0000
Epoch 32/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 24823895949312.0000 - mae: 4674374.0000 - val_loss: 24240661200896.0000 - val_mae: 4568811.0000
Epoch 33/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 24748199247872.0000 - mae: 4666740.0000 - val_loss: 24164685578240.0000 - val_mae: 4561041.5000
Epoch 34/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24665770688512.0000 - mae: 4658336.5000 - val_loss: 24080765943808.0000 - val_mae: 4552457.5000
Epoch 35/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24573315645440.0000 - mae: 4649059.5000 - val_loss: 23990225600512.0000 - val_mae: 4543152.5000
Epoch 36/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24474323779584.0000 - mae: 4638937.5000 - val_loss: 23890489245696.0000 - val_mae: 4532896.0000
Epoch 37/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24366752464896.0000 - mae: 4627876.0000 - val_loss: 23781332484096.0000 - val_mae: 4521674.5000
Epoch 38/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24248361943040.0000 - mae: 4615793.5000 - val_loss: 23663625633792.0000 - val_mae: 4509520.5000
Epoch 39/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24121473761280.0000 - mae: 4602718.0000 - val_loss: 23535875522560.0000 - val_mae: 4496306.5000
Epoch 40/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23981363036160.0000 - mae: 4588512.5000 - val_loss: 23400338685952.0000 - val_mae: 4482190.5000
Epoch 41/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23834988118016.0000 - mae: 4573296.5000 - val_loss: 23252478984192.0000 - val_mae: 4466806.5000
Epoch 42/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23675218690048.0000 - mae: 4556819.0000 - val_loss: 23094536175616.0000 - val_mae: 4450279.0000
Epoch 43/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 23505552801792.0000 - mae: 4539066.5000 - val_loss: 22924989825024.0000 - val_mae: 4432496.5000
Epoch 44/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23322270105600.0000 - mae: 4520011.5000 - val_loss: 22745098223616.0000 - val_mae: 4413526.0000
Epoch 45/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23128809930752.0000 - mae: 4499761.0000 - val_loss: 22552921505792.0000 - val_mae: 4393198.0000
Epoch 46/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 22922758455296.0000 - mae: 4478041.5000 - val_loss: 22348944113664.0000 - val_mae: 4371512.5000
Epoch 47/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 22704289742848.0000 - mae: 4454857.0000 - val_loss: 22132538998784.0000 - val_mae: 4348391.5000
Epoch 48/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 22472875311104.0000 - mae: 4430253.0000 - val_loss: 21904247226368.0000 - val_mae: 4323886.0000
Epoch 49/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 22224423616512.0000 - mae: 4404229.0000 - val_loss: 21667061432320.0000 - val_mae: 4298182.0000
Epoch 50/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 21974388572160.0000 - mae: 4376569.0000 - val_loss: 21409722007552.0000 - val_mae: 4270270.0000
Epoch 51/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 21698124447744.0000 - mae: 4347004.5000 - val_loss: 21145392775168.0000 - val_mae: 4241311.5000
Epoch 52/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 21419444404224.0000 - mae: 4316287.0000 - val_loss: 20864462487552.0000 - val_mae: 4210406.0000
Epoch 53/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 21118123507712.0000 - mae: 4283493.0000 - val_loss: 20574036295680.0000 - val_mae: 4178139.7500
Epoch 54/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 20810567778304.0000 - mae: 4249160.5000 - val_loss: 20268307185664.0000 - val_mae: 4143931.7500
Epoch 55/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 20487446986752.0000 - mae: 4212998.5000 - val_loss: 19949009502208.0000 - val_mae: 4107967.2500
Epoch 56/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 20147693682688.0000 - mae: 4174785.7500 - val_loss: 19620018782208.0000 - val_mae: 4070472.2500
Epoch 57/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 19794768166912.0000 - mae: 4135035.2500 - val_loss: 19281257431040.0000 - val_mae: 4031487.2500
Epoch 58/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 19436620742656.0000 - mae: 4093579.0000 - val_loss: 18924624150528.0000 - val_mae: 3990142.5000
Epoch 59/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 19056019111936.0000 - mae: 4049838.0000 - val_loss: 18560363528192.0000 - val_mae: 3947389.7500
Epoch 60/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 18669243465728.0000 - mae: 4004747.5000 - val_loss: 18182123290624.0000 - val_mae: 3902644.0000
Epoch 61/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 18275371057152.0000 - mae: 3957155.7500 - val_loss: 17786719961088.0000 - val_mae: 3855328.7500
Epoch 62/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 17854271324160.0000 - mae: 3907390.5000 - val_loss: 17389392494592.0000 - val_mae: 3807048.7500
Epoch 63/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 17430601531392.0000 - mae: 3856256.2500 - val_loss: 16982011281408.0000 - val_mae: 3756936.0000
Epoch 64/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 17005305397248.0000 - mae: 3803109.5000 - val_loss: 16556726681600.0000 - val_mae: 3704081.5000
Epoch 65/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 16558483046400.0000 - mae: 3747640.7500 - val_loss: 16125994729472.0000 - val_mae: 3649724.2500
Epoch 66/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 16103757578240.0000 - mae: 3690453.2500 - val_loss: 15689130704896.0000 - val_mae: 3593728.0000
Epoch 67/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 15648595902464.0000 - mae: 3631110.2500 - val_loss: 15240764850176.0000 - val_mae: 3535403.0000
Epoch 68/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 15175179567104.0000 - mae: 3569941.2500 - val_loss: 14790859685888.0000 - val_mae: 3475801.5000
Epoch 69/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 14704292397056.0000 - mae: 3506938.0000 - val_loss: 14331900067840.0000 - val_mae: 3414037.5000
Epoch 70/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 14224381181952.0000 - mae: 3441971.2500 - val_loss: 13868232343552.0000 - val_mae: 3350519.0000
Epoch 71/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 13741046366208.0000 - mae: 3375276.2500 - val_loss: 13399382556672.0000 - val_mae: 3285120.0000
Epoch 72/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 13257404317696.0000 - mae: 3306411.5000 - val_loss: 12925034037248.0000 - val_mae: 3217669.0000
Epoch 73/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 12759526801408.0000 - mae: 3235656.0000 - val_loss: 12455659962368.0000 - val_mae: 3149339.0000
Epoch 74/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 12273482465280.0000 - mae: 3163607.5000 - val_loss: 11980753600512.0000 - val_mae: 3078823.0000
Epoch 75/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11779994288128.0000 - mae: 3090154.0000 - val_loss: 11509128232960.0000 - val_mae: 3007256.5000
Epoch 76/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11289291128832.0000 - mae: 3015060.5000 - val_loss: 11040013156352.0000 - val_mae: 2934281.7500
Epoch 77/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10803480625152.0000 - mae: 2938380.2500 - val_loss: 10573321338880.0000 - val_mae: 2859866.2500
Epoch 78/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 10323629178880.0000 - mae: 2860505.5000 - val_loss: 10105470844928.0000 - val_mae: 2783514.2500
Epoch 79/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 9843479937024.0000 - mae: 2779992.7500 - val_loss: 9645939752960.0000 - val_mae: 2707577.0000
Epoch 80/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 9373382344704.0000 - mae: 2699988.5000 - val_loss: 9191829798912.0000 - val_mae: 2631193.0000
Epoch 81/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8907950915584.0000 - mae: 2618402.2500 - val_loss: 8746961469440.0000 - val_mae: 2554093.5000
Epoch 82/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8451178102784.0000 - mae: 2536437.0000 - val_loss: 8310933159936.0000 - val_mae: 2476042.5000
Epoch 83/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8002858385408.0000 - mae: 2453081.7500 - val_loss: 7886942502912.0000 - val_mae: 2397732.2500
Epoch 84/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7574622044160.0000 - mae: 2370259.7500 - val_loss: 7467869667328.0000 - val_mae: 2317945.5000
Epoch 85/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7147565875200.0000 - mae: 2286299.5000 - val_loss: 7064524423168.0000 - val_mae: 2238397.0000
Epoch 86/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6750454415360.0000 - mae: 2202269.5000 - val_loss: 6664015577088.0000 - val_mae: 2158345.0000
Epoch 87/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6345580871680.0000 - mae: 2117514.0000 - val_loss: 6288949379072.0000 - val_mae: 2083359.8750
Epoch 88/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5963704172544.0000 - mae: 2037115.7500 - val_loss: 5930590142464.0000 - val_mae: 2009685.8750
Epoch 89/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5596106981376.0000 - mae: 1956211.5000 - val_loss: 5591654203392.0000 - val_mae: 1937268.3750
Epoch 90/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5254578438144.0000 - mae: 1877170.3750 - val_loss: 5261449232384.0000 - val_mae: 1866532.0000
Epoch 91/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 4928601325568.0000 - mae: 1799473.6250 - val_loss: 4942702575616.0000 - val_mae: 1796140.7500
Epoch 92/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 4614758334464.0000 - mae: 1723294.8750 - val_loss: 4642153431040.0000 - val_mae: 1726724.0000
Epoch 93/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 4323464708096.0000 - mae: 1652743.3750 - val_loss: 4355589931008.0000 - val_mae: 1657463.5000
Epoch 94/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 4037203722240.0000 - mae: 1581500.3750 - val_loss: 4094593597440.0000 - val_mae: 1592550.8750
Epoch 95/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3784561131520.0000 - mae: 1515992.1250 - val_loss: 3844181065728.0000 - val_mae: 1527961.2500
Epoch 96/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3539786530816.0000 - mae: 1453708.5000 - val_loss: 3613944184832.0000 - val_mae: 1465747.2500
Epoch 97/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3315799949312.0000 - mae: 1395781.7500 - val_loss: 3400335622144.0000 - val_mae: 1407280.1250
Epoch 98/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3110051250176.0000 - mae: 1341741.3750 - val_loss: 3200942604288.0000 - val_mae: 1350785.1250
Epoch 99/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2917977292800.0000 - mae: 1290203.1250 - val_loss: 3018823303168.0000 - val_mae: 1301031.1250
Epoch 100/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2747928412160.0000 - mae: 1243275.6250 - val_loss: 2847804751872.0000 - val_mae: 1255753.1250

In [ ]:
y_pred=model.predict(x_test).flatten()

WARNING:tensorflow:5 out of the last 9 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7964de89c5e0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/4 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

WARNING:tensorflow:6 out of the last 12 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7964de89c5e0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

In [ ]:
y_pred

array([4663179. , 4462640. , 2635235. , 3382941.8, 2953029.2, 3404602. ,
       4316397.5, 4266328. , 2690692.5, 2677083.8, 6589316. , 2594815. ,
       2500043.5, 2980473. , 3167917.5, 4242946. , 2532839. , 3823405. ,
       3779839. , 2967063. , 3839971.2, 3407379.5, 2546564.5, 3405300.8,
       4552931.5, 5381324. , 2420202. , 3601139. , 5327777. , 2695360.5,
       3789107.2, 3331735.5, 4370186. , 3652275.5, 3656406.8, 4208244.5,
       3874474.5, 3376373.2, 2797528.5, 3934919. , 4227668.5, 2547434. ,
       4449096. , 3530274.5, 3094038.2, 3222842.5, 4637580. , 3949662.8,
       3291654. , 3009877.8, 5452097.5, 2730326.2, 3553582.5, 3221578.5,
       3450165.2, 2712637. , 4838945. , 2916202. , 3962458.2, 2572129. ,
       3662211.8, 3408095.8, 3926552.5, 2758517. , 3994770. , 3654994. ,
       4366257.5, 3003696.5, 5636982.5, 3797413. , 3505225. , 3842245.5,
       3660241.5, 4933440. , 2680913. , 4089872. , 3734189.8, 2760693.5,
       3596124.2, 3095819.8, 5364330. , 3810374.8, 4358853. , 3858168.8,
       2797692. , 4979594.5, 2740946. , 3410078.5, 5543787.5, 5539390.5,
       3454393.8, 3911465.5, 2867169.2, 3051127.5, 6440451.5, 3476551.5,
       4325467. , 4581245. , 3967810.5, 4320343. , 3668162.5, 4477464.5,
       3278153. , 4275732. , 4459462. , 4267953. , 5269333.5, 4427626. ,
       4478071.5], dtype=float32)

In [ ]:
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)

In [ ]:
print("MSE : ",mse)
print("MAE : ",mae)

MSE :  4385920516096.0
MAE :  1526816.875

In [ ]:
rmse=np.sqrt(mse)
print("RMSE : ",rmse)

RMSE :  2094258.9419878335

In [ ]:
new_house = pd.DataFrame({
    "area": [1400],
    "bedrooms": [3],
    "bathrooms": [3],
    "stories": [1],
    "mainroad":["yes"],
    "guestroom":["yes"],
    "basement":["yes"],
    "hotwaterheating":["yes"],
    "airconditioning":["yes"],
    "parking":[1],
    "prefarea":["yes"],
    "furnishingstatus":["unfurnished"]
})

In [ ]:
print("New House : ",new_house)

New House :     area  bedrooms  bathrooms  ...  parking prefarea furnishingstatus
0  1400         3          3  ...        1      yes      unfurnished

[1 rows x 12 columns]

In [ ]:
new_house_preprocessed=preprocessor.transform(new_house)

In [ ]:
predicted_price=model.predict(new_house_preprocessed)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step

In [ ]:
print("Predicted price : ",predicted_price[0][0])

Predicted price :  3857657.2